spring.application.name=proyectoInicialSpring
spring.datasource.url=jdbc:mysql://192.168.1.20:3306/empleados
spring.datasource.username=marcelo
spring.datasource.password=R2daH$R4urL
spring.jpa.hibernate.ddl-auto=update